<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MineRailMonitor.Core\MineRailMonitor.Core.csproj" />
    <ProjectReference Include="..\MineRailMonitor.Infrastructure\MineRailMonitor.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Projects\**\*" Link="Projects\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>

</Project>
